//! Showcase: FreeSWITCH event SUBSCRIPTION via `fswtch::EventBinder` + `fswtch::event_callback!`.
//!
//! At module load this subscribes to `SWITCH_EVENT_CHANNEL_CREATE` (fired whenever a new channel
//! is created) and keeps the subscription live for the module's lifetime. The `event_callback!`
//! body reads the `Unique-ID` header off the incoming event via [`fswtch::EventRef::header`] and
//! bumps an [`AtomicU64`] counter.
//!
//! Register an API command to inspect the count:
//!
//! ```text
//! load mod_event_listener
//! fs_cli -x 'fswtch_event_status'
//! ```
//!
//! then originate a call (e.g. `originate user/1000 &echo`) and re-run `fswtch_event_status` to see
//! the counter climb as `CHANNEL_CREATE` events arrive.

use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};

/// Total number of `CHANNEL_CREATE` events observed since the module loaded. Incremented from the
/// event callback (which FreeSWITCH invokes on its own thread).
static EVENTS_SEEN: AtomicU64 = AtomicU64::new(0);

/// Whether the `CHANNEL_CREATE` subscription is bound. The [`fswtch::EventBinder`] guard itself
/// is not `Send` (it owns a `NonNull`), so it cannot live in a `static`; instead the guard is
/// leaked for the module's lifetime (matching how `module.rs` leaks static interface names) and
/// only this `Send` flag is shared with the event thread.
static BOUND: AtomicBool = AtomicBool::new(false);

// FreeSWITCH event callback for `SWITCH_EVENT_CHANNEL_CREATE`. Generated by `event_callback!`
// into an `unsafe extern "C" fn(*mut switch_event_t)` matching `switch_event_callback_t`. The
// body reads the `Unique-ID` header and bumps the counter; logging is best-effort because the
// callback fires on FreeSWITCH's event thread.
fswtch::event_callback! {
    fn on_channel_create(event) {
        EVENTS_SEEN.fetch_add(1, Ordering::Relaxed);
        let uuid = event.header("Unique-ID").unwrap_or_else(|| "<unknown>".to_owned());
        fswtch::log_info(
            "mod_event_listener",
            format!("CHANNEL_CREATE received (uuid={uuid})"),
        );
    }
}

fswtch::module_exports! {
    module = mod_event_listener,
    load = switch_module_load,
}

fswtch::api_callback! {
    fn status_api(_cmd, _session, stream) {
        fswtch::log_info("mod_event_listener", "fswtch_event_status invoked");
        let Some(stream) = stream else {
            return fswtch::FALSE;
        };
        let bound = BOUND.load(Ordering::Relaxed);
        let seen = EVENTS_SEEN.load(Ordering::Relaxed);
        stream.write(&format!(
            "event_listener: subscribed={} channel_create_events={seen}\n",
            if bound { "yes" } else { "no" },
        ))
    }
}

fswtch::module_load! {
    fn switch_module_load(module) for "mod_event_listener" {
        fswtch::log_info("mod_event_listener", "loading module");

        // Subscribe to SWITCH_EVENT_CHANNEL_CREATE. The binder guard is leaked for the module's
        // lifetime so the subscription outlives load (it cannot live in a `static` because it is
        // not `Send`). No user_data is threaded through because FreeSWITCH's event callback
        // signature does not pass it back to the callback (see fswtch::EventBinder docs).
        fswtch::EventBinder::bind(
            "mod_event_listener",
            fswtch::EventType::CHANNEL_CREATE,
            None,
            Some(on_channel_create),
            std::ptr::null_mut(),
        )
        .map(|binder| {
            // Leak the guard so the subscription survives for the module's lifetime.
            std::mem::forget(binder);
            BOUND.store(true, Ordering::Relaxed);
            fswtch::log_info("mod_event_listener", "CHANNEL_CREATE subscription bound");
        })
        .and_then(|()| {
            module.api(
                "fswtch_event_status",
                "reports how many CHANNEL_CREATE events the Rust listener has seen",
                "fswtch_event_status",
                status_api,
            )
        })
    }
}
