//! FreeSWITCH event subscription — receive external `CUSTOM voice_seat::command`
//! events and dispatch them to the matching CallActor by UUID.
//!
//! This crate uses [`fswtch::EventBinder`] — the RAII guard returned by
//! [`fswtch::EventBinder::bind`] — together with the [`fswtch::event_callback!`]
//! macro that generates the C trampoline FreeSWITCH invokes. Dropping the guard
//! calls `switch_event_unbind`, revoking the subscription.
//!
//! ## Event contract
//!
//! ```text
//! sendevent CUSTOM voice_seat::command  \
//!   Unique-ID: <uuid>  Action: <op>  [Digits: <digits>]
//! ```
//!
//! - `Action: hangup`     → [`HangupCall`](crate::call_core::HangupCall) (stop the actor / end the call)
//! - `Action: send_dtmf`  → [`SendDtmf`](crate::call_core::SendDtmf)  (requires `Digits` header)
//! - `<other>`            → warning log, no-op (extensible: add a match arm)
//!
//! Send from `fs_cli` / an ESL connection / the control plane:
//! ```text
//! fs_cli -x "sendevent CUSTOM 'voice_seat::command' Unique-ID: <uuid> Action: hangup"
//! ```
//!
//! Dispatch is fire-and-forget: the callback looks up the CallActor via
//! [`registry().get(uuid)`](crate::call_core::registry) and `do_send`s an actix
//! message. `do_send` from an arbitrary FS event thread is safe — actix `Addr`
//! is `Send + Sync` and the message queues into the actor's mailbox on the
//! module's actix System.
//!
//! The callback runs on an FS event-delivery thread, so it is wrapped in
//! [`boundary::catch_fs`] so a panic degrades to "drop this event" instead of
//! aborting the FreeSWITCH process.

use std::sync::{Mutex, OnceLock};

use fswtch::{EventBinder, Result, sys};

use crate::boundary;
use crate::call_core::{HangupCall, SendDtmf, registry};

/// The CUSTOM subclass name events are bound to.
const SUBCLASS: &str = "voice_seat::command";

/// The bind id (FreeSWITCH event node tag).
const BIND_ID: &str = "ai_agent_seat";

/// Slot holding the bound [`EventBinder`] guard.
///
/// Stored behind a [`Mutex`] (rather than `OnceLock<Option<T>>` directly) so
/// [`unbind()`] can take the guard out and drop it — `OnceLock` only hands out
/// shared references and cannot release its contents, but a `Mutex<Option<T>>`
/// lets us swap the guard to `None` at shutdown, triggering its `Drop` (which
/// calls `switch_event_unbind`). Mirrors the `Mutex<Option<Runtime>>` pattern
/// used in [`crate::actor`] for the tokio runtime.
///
/// `EventBinder` owns a `NonNull<switch_event_node_t>`, which is not `Send` by
/// default (raw pointers aren't). It is safe to move between threads here: the
/// guard only swaps in/out under the `Mutex`, and FreeSWITCH invokes the
/// callback on its own event-delivery thread regardless of which thread holds
/// the Rust handle. See the reference module for the same pattern.
static BINDER: OnceLock<Mutex<Option<SendBinder>>> = OnceLock::new();

/// `EventBinder` wrapper that is `Send` for static storage. See [`BINDER`] docs.
#[allow(dead_code)]
struct SendBinder(EventBinder);
unsafe impl Send for SendBinder {}

fn slot() -> &'static Mutex<Option<SendBinder>> {
    BINDER.get_or_init(|| Mutex::new(None))
}

/// Bind to `CUSTOM voice_seat::command` events.
///
/// Call from `do_module_load` AFTER `actor::start_runtime()` so a fast event
/// can't race a pending actix System. Stores the [`EventBinder`] guard in the
/// slot so [`unbind()`] can drop (and thus unbind) it later. Returns an error if
/// `fswtch::EventBinder::bind` fails, or if [`bind()`] was already called (the
/// existing subscription is left untouched in that case).
pub fn bind() -> Result<()> {
    let mut guard = slot().lock().unwrap();
    if guard.is_some() {
        tracing::warn!("event_sub::bind() called twice; keeping the existing subscription");
        return Ok(());
    }

    let binder = EventBinder::bind(
        BIND_ID,
        sys::switch_event_types_t::SWITCH_EVENT_CUSTOM,
        Some(SUBCLASS),
        Some(on_command),
        std::ptr::null_mut(),
    )?;

    *guard = Some(SendBinder(binder));
    tracing::info!("bound to {} events", SUBCLASS);
    Ok(())
}

/// Unbind from `CUSTOM voice_seat::command` events.
///
/// Call from `switch_module_shutdown` BEFORE `actor::stop_runtime()` — prevents
/// an in-flight event callback from entering unloaded code. Dropping the
/// [`EventBinder`] guard calls `switch_event_unbind`. No-op if [`bind()`] was
/// never called or already unbound.
pub fn unbind() {
    let taken = slot().lock().unwrap().take();
    if taken.is_some() {
        tracing::info!("unbound {} events", SUBCLASS);
    }
}

// Callback for `CUSTOM voice_seat::command`. Runs on an FS event thread.
//
// Generated by the [`fswtch::event_callback!`] macro, which wraps the raw
// `*mut switch_event_t` in an [`fswtch::EventRef`] for the body. The body is
// wrapped in [`boundary::catch_fs`] so a panic degrades to "drop this event".
fswtch::event_callback! {
    fn on_command(event) {
        boundary::catch_fs(|| {
            // `event` is an `EventRef` (the macro wraps the raw pointer).
            // `EventRef::header` borrows the event's storage for the callback.
            let Some(uuid) = event.header("Unique-ID") else {
                tracing::warn!("voice_seat::command event missing Unique-ID header");
                return;
            };
            let action = event.header("Action").unwrap_or_default();

            let Some(addr) = registry().get(&uuid) else {
                tracing::debug!(
                    "voice_seat::command {} for {}: no active CallActor",
                    action,
                    uuid
                );
                return;
            };

            match action.as_str() {
                "hangup" => {
                    tracing::info!("voice_seat::command hangup → {}", uuid);
                    addr.do_send(HangupCall {
                        uuid: uuid.clone(),
                        cause: None,
                    });
                }
                "send_dtmf" => {
                    let digits = event.header("Digits").unwrap_or_default();
                    if digits.is_empty() {
                        tracing::warn!(
                            "voice_seat::command send_dtmf for {}: missing Digits header",
                            uuid
                        );
                        return;
                    }
                    tracing::info!(
                        "voice_seat::command send_dtmf '{}' → {}",
                        digits,
                        uuid
                    );
                    addr.do_send(SendDtmf {
                        uuid: uuid.clone(),
                        digits,
                        duration_ms: None,
                    });
                }
                other => {
                    tracing::warn!(
                        "unknown voice_seat::command Action '{}' for {}",
                        other,
                        uuid
                    );
                }
            }
        });
    }
}
