//! FreeSWITCH event subscription — receive external `CUSTOM voice_seat::command`
//! events and execute control actions on the matching call by UUID.
//!
//! In the Endpoint-module design there are no actix actors to dispatch to.
//! This module binds to the `voice_seat::command` CUSTOM event and, for each
//! inbound event, checks [`crate::call_core::is_live_call`] for the UUID, then
//! invokes the [`CallControl`](crate::call_core::CallControl) singleton
//! ([`crate::control::FfiControl`]) directly: `Action: hangup` →
//! [`CallControl::hangup`], `Action: send_dtmf` → [`CallControl::send_dtmf`].
//!
//! This crate uses [`fswtch::EventBinder`] — the RAII guard returned by
//! [`fswtch::EventBinder::bind`] — together with the [`fswtch::event_callback!`]
//! macro that generates the C trampoline FreeSWITCH invokes. Dropping the guard
//! calls `switch_event_unbind`, revoking the subscription.
//!
//! ## Event contract
//!
//! ```text
//! sendevent CUSTOM voice_seat::command  \
//!   Unique-ID: <uuid>  Action: <op>  [Digits: <digits>]
//! ```
//!
//! - `Action: hangup`     → [`CallControl::hangup`](crate::call_core::CallControl::hangup)
//! - `Action: send_dtmf`  → [`CallControl::send_dtmf`](crate::call_core::CallControl::send_dtmf) (requires `Digits` header)
//! - `<other>`            → warning log, no-op (extensible: add a match arm)
//!
//! Send from `fs_cli` / an ESL connection / the control plane:
//! ```text
//! fs_cli -x "sendevent CUSTOM 'voice_seat::command' Unique-ID: <uuid> Action: hangup"
//! ```
//!
//! The callback runs on an FS event-delivery thread, so it is wrapped in
//! [`boundary::catch_fs`] so a panic degrades to "drop this event" instead of
//! aborting the FreeSWITCH process.

use std::sync::{Mutex, OnceLock};

use fswtch::{EventBinder, Result};

use crate::boundary;
use crate::call_core::{control, is_live_call};

/// The CUSTOM subclass name events are bound to.
const SUBCLASS: &str = "voice_seat::command";

/// The bind id (FreeSWITCH event node tag).
const BIND_ID: &str = "ai_agent_seat";

/// Slot holding the bound [`EventBinder`] guard.
///
/// Stored behind a [`Mutex`] (rather than `OnceLock<Option<T>>` directly) so
/// [`unbind()`] can take the guard out and drop it — `OnceLock` only hands out
/// shared references and cannot release its contents, but a `Mutex<Option<T>>`
/// lets us swap the guard to `None` at shutdown, triggering its `Drop` (which
/// calls `switch_event_unbind`).
///
/// `EventBinder` owns a `NonNull<switch_event_node_t>`, which is not `Send` by
/// default (raw pointers aren't). It is safe to move between threads here: the
/// guard only swaps in/out under the `Mutex`, and FreeSWITCH invokes the
/// callback on its own event-delivery thread regardless of which thread holds
/// the Rust handle.
static BINDER: OnceLock<Mutex<Option<SendBinder>>> = OnceLock::new();

/// `EventBinder` wrapper that is `Send` for static storage. See [`BINDER`] docs.
#[allow(dead_code)]
struct SendBinder(EventBinder);
unsafe impl Send for SendBinder {}

fn slot() -> &'static Mutex<Option<SendBinder>> {
    BINDER.get_or_init(|| Mutex::new(None))
}

/// Bind to `CUSTOM voice_seat::command` events.
///
/// Call from `do_module_load` AFTER [`crate::actor::start_runtime`] so a fast
/// event can't race a pending runtime. Stores the [`EventBinder`] guard in the
/// slot so [`unbind()`] can drop (and thus unbind) it later. Returns an error
/// if `fswtch::EventBinder::bind` fails, or if [`bind()`] was already called
/// (the existing subscription is left untouched in that case).
pub fn bind() -> Result<()> {
    let mut guard = slot().lock().unwrap();
    if guard.is_some() {
        tracing::warn!("event_sub::bind() called twice; keeping the existing subscription");
        return Ok(());
    }

    let binder = EventBinder::bind(
        BIND_ID,
        fswtch::EventType::CUSTOM,
        Some(SUBCLASS),
        Some(on_command),
        std::ptr::null_mut(),
    )?;

    *guard = Some(SendBinder(binder));
    tracing::info!("bound to {} events", SUBCLASS);
    Ok(())
}

/// Unbind from `CUSTOM voice_seat::command` events.
///
/// Call from `switch_module_shutdown` BEFORE [`crate::actor::stop_runtime`] —
/// prevents an in-flight event callback from entering unloaded code. Dropping
/// the [`EventBinder`] guard calls `switch_event_unbind`. No-op if [`bind()`]
/// was never called or already unbound.
pub fn unbind() {
    let taken = slot().lock().unwrap().take();
    if taken.is_some() {
        tracing::info!("unbound {} events", SUBCLASS);
    }
}

// Callback for `CUSTOM voice_seat::command`. Runs on an FS event thread.
//
// Generated by the [`fswtch::event_callback!`] macro, which wraps the raw
// `*mut switch_event_t` in an [`fswtch::EventRef`] for the body. The body is
// wrapped in [`boundary::catch_fs`] so a panic degrades to "drop this event".
fswtch::event_callback! {
    fn on_command(event) {
        boundary::catch_fs(|| {
            // `event` is an `EventRef` (the macro wraps the raw pointer).
            // `EventRef::header` borrows the event's storage for the callback.
            let Some(uuid) = event.header("Unique-ID") else {
                tracing::warn!("voice_seat::command event missing Unique-ID header");
                return;
            };
            let action = event.header("Action").unwrap_or_default();

            if !is_live_call(&uuid) {
                tracing::debug!(
                    "voice_seat::command {} for {}: no active call",
                    action,
                    uuid
                );
                return;
            }

            let control = control();
            match action.as_str() {
                "hangup" => {
                    tracing::info!("voice_seat::command hangup → {}", uuid);
                    if let Err(e) = control.hangup(&uuid) {
                        tracing::warn!("voice_seat::command hangup failed for {uuid}: {e}");
                    }
                }
                "send_dtmf" => {
                    let digits = event.header("Digits").unwrap_or_default();
                    if digits.is_empty() {
                        tracing::warn!(
                            "voice_seat::command send_dtmf for {}: missing Digits header",
                            uuid
                        );
                        return;
                    }
                    tracing::info!(
                        "voice_seat::command send_dtmf '{}' → {}",
                        digits,
                        uuid
                    );
                    if let Err(e) = control.send_dtmf(&uuid, &digits) {
                        tracing::warn!("voice_seat::command send_dtmf failed for {uuid}: {e}");
                    }
                }
                other => {
                    tracing::warn!(
                        "unknown voice_seat::command Action '{}' for {}",
                        other,
                        uuid
                    );
                }
            }
        });
    }
}
